name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Getting code
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Installing dependencies
        if: ${{ !steps.node-modules-cache.outputs.cache-hit }}
        run: npm ci
      - name: Caching build folder
        uses: actions/cache@v3
        id: build-folder-cache
        with:
          path: |
            dist/linux-unpacked
            dist/builder-effective-config.yaml
          key: build-${{ hashFiles('dist/builder-effective-config.yaml') }}
      - name: Building for linux
        run: npm run dist
      - name: Creating new release
        id: create-release
        run: |
          response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{"tag_name":"${{ github.ref_name }}","name":"${{ github.ref_name }}","body":"description","draft":true}') && \
          echo release_id=$(echo $response | jq -r '.id') >> $GITHUB_OUTPUT
      - name: Uploading release binary
        run: |
          version_number=$(echo ${{ github.ref_name }} | tr -d "v") && \
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/vnd.debian.binary-package" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create-release.outputs.release_id }}/assets?name=clipboard_${version_number}_amd64.deb" \
          --data-binary "@dist/clipboard_${version_number}_amd64.deb"